### ISSUE TITLE
Templatelerde repetitive code yapmamak için tema yazıp importlamak

### ISSUE THREAD

**Issue by berkbuzcu** [lyk2017-django/ChittyChatter#5]
Açıklayıcı başlık

**Comment by berkbuzcu** [comment]
Settings ve Context_Processors a dikkat isteyen alabilir

**Comment by ghost** [comment]
Burası bende, ilk boşlukta context processer'ü ve base'i yazıp diğer sayfaları düzenleyeceğim.
